// create new products
export const ADD_PRODUCT_INIT = 'ADD_PRODUCT_INIT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

// get products
export const GET_PRODUCTS_INIT = 'GET_PRODUCTS_INIT';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

// set active product
export const SET_ACTIVE_INIT = 'SET_ACTIVE_INIT';
export const SET_ACTIVE_REMOVED = 'SET_ACTIVE_REMOVED';

// delete products
export const REMOVE_PRODUCT_INIT = 'REMOVE_PRODUCT_INIT';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_ABORT = 'REMOVE_PRODUCT_ABORT';
export const REMOVE_PRODUCT_FAIL = 'REMOVE_PRODUCT_FAIL';
